### ISSUE TITLE
Identify Cupper project

### ISSUE THREAD

**Issue by paulohtfs** [cupper-reverse-recipe/cupper#11]
Working Branch [issue11_idenif_proj](https://github.com/cupper-reverse-recipe/cupper/tree/issue11_idenif_proj)

All command lines must know if it's on Cupper project directory.

If you run a command outside of a directory of a cupper project (meaning a directory without a Cupperfile) and error message should be displayed.

For that we have to implement an exception handling class, a YML file with the error messages, an enviroment class to set the directory as an working environment, and a Cupperfile class to handle this config file secification.

Then we need to raise the corresponding exception if no env is set.

- [x] Excption Handling class

- [x] YML messages

- [x] Env class

- [x] Cupperfile class

- [x] Raise exception

- [x] Error printer for the user

**Comment by aldarionsevero** [comment]
Using the vagrant Exception handling strategy, we defined the error messages anticipating localization as a future issue.

**Comment by aldarionsevero** [comment]
Setting an environment as a working directory with your config files. Also a Vagrant strategy.

**Comment by aldarionsevero** [comment]
Anticipating some attributes and methods for and Cupperfile class that handles this important configuration file for Cupper.

**Comment by aldarionsevero** [comment]
The Exception is raised correctly if a Cupperfile is not present. We still need to implement some "error printer" to generalize the output.

**Comment by aldarionsevero** [comment]
Errors being handled in the env class. Not sure if it is the best approach.

**Comment by aldarionsevero** [comment]
The important methods of finding cupperfile and definig env are tested.
