### ISSUE TITLE
Extract Users

### ISSUE THREAD

**Issue by paulohtfs** [cupper-reverse-recipe/cupper#18]
Reference to #12

The full list of attributes  is:

**comment**                    String
**force**                      TrueClass, FalseClass # see description
**gid**                        String, Integer
**home**                       String
**iterations**                 Integer
**manage_home**                TrueClass, FalseClass
**non_unique**                 TrueClass, FalseClass
**notifies**                   # see description
**password**                   String
**provider**                   Chef::Provider::User
**salt**                       String
**shell**                      String
**supports**                   Hash
**subscribes**                 # see description
**system**                    TrueClass, FalseClass
**uid**                        String, Integer
**username**                   String # defaults to 'name' if not specified
**action**                     Symbol # defaults to :create if not specified

The desired attributes for the user extraction are:

- [x] username

- [x] group

- [x] group id

- [x] home dir

- [x] manage_home

- [x] password

- [x] shell

- [x] supports?

- [x] system_user

- [x] user id

**Comment by aldarionsevero** [comment]
The full list of attributes  is:

**comment**                    String
**force**                      TrueClass, FalseClass # see description
**gid**                        String, Integer
**home**                       String
**iterations**                 Integer
**manage_home**                TrueClass, FalseClass
**non_unique**                 TrueClass, FalseClass
**notifies**                   # see description
**password**                   String
**provider**                   Chef::Provider::User
**salt**                       String
**shell**                      String
**supports**                   Hash
**subscribes**                 # see description
**system**                    TrueClass, FalseClass
**uid**                        String, Integer
**username**                   String # defaults to 'name' if not specified
**action**                     Symbol # defaults to :create if not specified


The desired attributes for the user extraction are:

- [ ] username

- [ ] group

- [ ] group id

- [ ] home dir

- [ ] manage_home

- [ ] password

- [ ] shell

- [ ] supports?

- [ ] system_user

- [ ] user id

**Comment by aldarionsevero** [comment]
We can get by the existing providers "etc" and "current_user" from ohai. No need for a new plugin.
