### ISSUE TITLE
Create a controlled environment

### ISSUE THREAD

**Issue by paulohtfs** [cupper-reverse-recipe/cupper#33]
[For testing and validation propose]

Create a box for vagrant, using virtualbox provider, with a minimal packages installed.
Create a checklist of application installed and configurations made.
- [x] Box with Debian 8 Jessie
- [x] Box with Arch Linux

**Comment by aldarionsevero** [comment]
Baseline for te boxes:

* nginx and default configuration
* postgres
* cups and some default configuration
* nginx providing cups as an example

**Comment by aldarionsevero** [comment]
Stop this approach, start testing in a real environment like the FGA moodle VM
